# https://docs.github.com/en/actions
---
name: Coding Standards

on:
  push:
    branches: [ main ]
    paths:
      - '**.php'
      - 'composer.json'
      - '.config/php-cs-fixer.php'
  pull_request:
    paths:
      - '**.php'
      - 'composer.json'
      - '.config/php-cs-fixer.php'

jobs:
  composer-normalize:
    name: Normalize composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Normalize composer.json
        uses: composer normalize --diff --dry-run

  php-cs-fixer:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Create cache directory
        run: mkdir -p .build/php-cs-fixer
      - name: Run PHP CS Fixer
        run: composer fix-style -- --dry-run
