name: Documentation

on:
  push:
    paths:
      - "docs/**"
      - .github/workflows/docs.yml
  pull_request:
    paths:
      - "docs/**"
      - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        working-directory: docs
        run: npm ci
      - name: Build documentation
        working-directory: docs
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/.vitepress/dist
  deploy:
    needs: "build"
    name: Deploy documentation
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: documentation
          path: documentation
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documentation
