name: Release

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: ["completed"]
    branches: ["main"]

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Run release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          package-name: 'hedger/skeleton'
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
