# https://docs.github.com/en/actions
---
name: Static Analysis

on:
  push:
    branches: [ main ]
    paths:
      - '**.php'
      - 'composer.json'
      - '.config/phpstan.neon'
  pull_request:
    paths:
      - '**.php'
      - 'composer.json'
      - '.config/phpstan.neon'

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Run PHPStan
        run: composer analyse
