# https://docs.github.com/en/actions
---
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        php: [ '8.1' ]
        dependency-versions: [ highest, lowest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Set up problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependency-versions }}
      - name: Run PHPUnit
        run: composer test

